### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by zeno-franco** [codeformilwaukee/hack-night-digital-programs#1]
Thanks for the orientation tonight.  I am not sure if this is the right place to put an "issue" to say hello, but going for it anyway.

Zeno Franco
Associate Professor
Family & Community Medicine
Medical College of Wisconsin

Interested in how I can help connect this group to funding, etc.

**Comment by BarkleyBG** [comment]
@zeno-franco, thank you for reaching out! This was a great message to receive - we are so happy for the engagement. I will be reaching out soon to chat and see how we can work together. Thank you for the message and thank you for attending!
